collections:
  species:
    output: true
  locations:
    output: true
  games:
    output: true
  characters:
    output: true
  concepts:
    output: true
  irl:
    output: true
  misc:
    output: true
